name: API-CBv6-V2-CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  auth-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run API tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run auth-ci
