name: API-CBv6-test-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Dusty:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
    - name: Run API tests
      env:
        BASE_URL: ${{ BASE_URL }}
        EMAIL: ${{ EMAIL }}
        PASSWORD: ${{ PASSWORD }}
      run: npm run test
